platform :ios, ‘8.0’
target ’bsbdj’ do
pod ‘AFNetworking’, ‘~>3.1.0’
pod 'DACircularProgress', '~>2.3.1'
pod 'MJRefresh', '~>3.1.12'
pod 'MJExtension', '~>3.0.13'
pod 'SDWebImage', '~>3.8.1'
pod 'SVProgressHUD', '~>2.0.3'
pod 'pop', '~>1.0.9'
end